### ISSUE TITLE
Volume has significally decreased in some games on release 20200524.  

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/ColecoVision_MiSTer#14]
King's Valley and SHMUP are two games which requires the SGM module and are good examples of games that are affected by this  significant volume decrease vs previous build.  What is weird is the games not affected are actually louder than the previous build, so something is not quite right. 

The problem is if you crank the volume for games affected like King's Valley than other games will be too loud and you are playing a game of turning up and down the volume on your remote at a per game level.  Even so, I'm pretty sure these significant volume inconsistencies are not normal and was not an issue on previous builds.

**Comment by rampa069** [comment]
ok. problem with the mix of AY and SN. working on it. thanks.

 Games using AM modulation (for example dragons lair) will sound OK now. but didnt try the SGM mix. sorry.

**Comment by rampa069** [comment]
found the problem. the sgm volume is the same as always.... the coleco volume is higher. making some changes to equilibrate.

**Comment by rampa069** [comment]
Can you please test this core before sending the pull request to the main repo?

https://github.com/rampa069/ColecoVision_MiSTer/blob/master/releases/ColecoVision_20220526.rbf

**Comment by SegaSnatcher** [comment]
> Can you please test this core before sending the pull request to the main repo?
> 
> https://github.com/rampa069/ColecoVision_MiSTer/blob/master/releases/ColecoVision_20220526.rbf

I tested it.  Unfortunately something appears broken with SGM now.  I don't hear any music in SHMUP and King's Valley keeps telling me the game requires the SGM module even when I have SGM enabled, so it won't even run now.

**Comment by rampa069** [comment]
where can i get this roms?

**Comment by SegaSnatcher** [comment]
> I think all is working now. Can you test now? (same file and url)

Yes, everything I tried is working as expected now.  Great work, thanks!

**Comment by rampa069** [comment]
thanks to you. i was thinking SGM was the same as SG1000 :-(
HAve learned a lot with this issue. now i have to put the same on Coleco ADAM. Thanks again.

**Comment by SegaSnatcher** [comment]
I will close this issue when commit is merged and with new release.
