### ISSUE TITLE
Feature Request:  Ability to fill the image completely vertically. 

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/ColecoVision_MiSTer#7]
Even with the scaler set to fill screen, Colecovision games still have huge black bars on top and bottom.  Its almost like this core is outputting a 192 vertical resolution in a 240p image, as you can see with the image below.  It would be nice if we could trim those blank scanlines.  A feature like "Hide Overscan" found in the NES core would be nice.

Edit, it appears SMS core has a feature called "Hide Borders" which will completely fill 192 vertical image for both SMS and SG-1000 games, so I guess its this feature I would like to see ported to Coleco core, thanks.

![image0 (10)](https://user-images.githubusercontent.com/36483667/104203690-0a9a2f80-53f2-11eb-805f-8c70c4eddb27.jpg)

**Comment by sorgelig** [comment]
are you talking about HDMI output?

**Comment by sorgelig** [comment]
i'm going to update this core with new framework - it will have option "full screen"

**Comment by SegaSnatcher** [comment]
Thank You Sorgelig, much appreciated.
